name: Build WSA Magisk
on:
  workflow_dispatch:
  repository_dispatch:
    types: [build]

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build WSA
    strategy:
      matrix:
        arch: [x64]
        root: [none]
        gapps: [MindTheGapps]
        release: [retail]
        compress-format: [7z]
        # arch: [x64, arm64]
        # root: [magisk, none]
        # gapps: [MindTheGapps, none]
        # release: [retail, WIF]
        # compress-format: [7z]
      fail-fast: false

    uses: ./.github/workflows/build_call.yml
    with:
      arch: ${{ matrix.arch }}
      release-type: ${{ matrix.release }}
      gapps-brand: ${{ matrix.gapps }}
      root-sol: ${{ matrix.root }}
      compress-format: ${{ matrix.compress-format }}
