name: Build WSA Magisk
on:
  workflow_dispatch:
  repository_dispatch:
    types: [build]

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build WSA
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, arm64]
        root: [magisk, none]
        gapps: [MindTheGapps, none]
        release: [retail]
        compress-format: [7z]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y whiptail lzip patchelf e2fsprogs python3-pip p7zip-full attr qemu-utils unzip sudo
          python3 -m pip install -r scripts/requirements.txt -q

      - name: Grant executable permission
        run: chmod +x ./scripts/build.sh

      - name: Build WSA GAPPS ${{ matrix.root }} ${{ matrix.arch }}
        id: wsa
        run: ./scripts/build.sh --arch ${{ matrix.arch }} --release-type ${{ matrix.release }} --magisk-ver stable --gapps-brand ${{ matrix.gapps }} --root-sol ${{ matrix.root }} --compress-format ${{ matrix.compress-format }}

      - name: Prepare release tag
        id: date
        run: echo "date=$(date +'v%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Pass to Windows
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.wsa.outputs.artifact }}.${{ matrix.compress-format }}
          path: ./output/${{ steps.wsa.outputs.artifact }}.${{ matrix.compress-format }}

  compress-vhdx:
    name: Compress to VHDX
    runs-on: windows-2022
    steps:

      - name: Download raw zip
        uses: actions/download-artifact@v3
        with:
          name: ${{ Write-Host '$1' >steps.wsa.outputs.artifact }}.${{ Write-Host '$1' >matrix.compress-format }}
          path: ./output

      - name: Convert to VHDX
        run: |
          pwsh.exe -ExecutionPolicy RemoteSigned .\zip2vhdx\zip2vhdx.ps1

      - name: Remove unused artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: ${{ Write-Host '$1' >steps.wsa.outputs.artifact }}.${{ Write-Host '$1' >matrix.compress-format }}

      - name: Upload build to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ Write-Host '$1' >steps.wsa.outputs.artifact }}.vhdx
          tag: ${{ Write-Host '$1' >steps.date.outputs.date }}
          overwrite: true
          file_glob: true
