name: Build WSA Magisk
on:
  workflow_call:
    inputs:
      arch:
        type: choice
        description: Architecture of WSA.
        required: true
        options: [x64, arm64]
        default: x64
      release-type:
        type: choice
        description: Release type of WSA. RP = Release Preview; WIS = Insider Slow; WIF = Insider Fast
        required: true
        options: ["retail","RP","WIS","WIF"]
        default: "retail"
      magisk-ver:
        type: choice
        description: Magisk version.
        required: true
        options: ["stable","beta","canary","debug"]
        default: "stable"
      gapps-brand:
        type: choice
        description: GApps brand. none for no integration of GApps
        required: true
        options: ["OpenGApps","MindTheGapps","none"]
        default: "MindTheGapps"
      gapps-variant:
        type: choice
        description: GApps variant.
        required: true
        options: ["super","stock","full","mini","micro","nano","pico","tvstock","tvmini"]
        default: "pico"
      root-sol:
        type: choice
        description: Root solution. none means no root.
        required: true
        options: ["magisk","none"]
        default: "magisk"
      compress-format:
        type: choice
        description: Compress format.
        required: true
        options: ["zip","7z"]
        default: "7z"

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build WSA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y whiptail lzip patchelf e2fsprogs python3-pip p7zip-full attr qemu-utils unzip sudo
          python3 -m pip install -r scripts/requirements.txt -q

      - name: Grant executable permission
        run: chmod +x ./scripts/build.sh

      - name: Build WSA GAPPS ${{ inputs.arch }}
        id: wsa
        run: ./scripts/build.sh --arch ${{ inputs.arch }} --release-type ${{ inputs.release-type }} --magisk-ver ${{ inputs.magisk-ver }} --gapps-brand ${{ inputs.gapps-brand }} --gapps-variant ${{ inputs.gapps-variant }} --root-sol ${{ inputs.root-sol }} --remove-amazon --compress-format ${{ inputs.compress-format }}

      - name: Pass to Windows
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.wsa.outputs.artifact }}.${{ inputs.compress-format }}
          path: ./output/${{ steps.wsa.outputs.artifact }}.${{ inputs.compress-format }}

  compress-vhdx:
    name: Compress to VHDX
    runs-on: windows-2022
    needs: build
    steps:

      - name: Download raw zip
        uses: actions/download-artifact@v3
        with:
          path: ./output

      - name: Convert to VHDX
        id: convert
        run: |
          pwsh.exe -ExecutionPolicy RemoteSigned .\zip2vhdx\convert.ps1

      - name: Remove unused artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: ${{ steps.wsa.outputs.artifact }}.${{ matrix.compress-format }}
